### register

POST http://localhost:3000/auth/register
content-type: application/json

{
    "name": "Patient",
    "email": "patient@xord.com",
    "password": "saltExample",
    "type": 1
}

### login

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email":"patient@xord.com",
    "password":"saltExample"
}

### accessing a protected route

GET http://localhost:3000/auth/protected
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmlqYTEiLCJzdWIiOiJyaWphMUB4b3JkLmNvbSIsInR5cGUiOjAsImlhdCI6MTY0MzY2NjExNn0.pNzBkeSLxmHIpnQ0D5TX3DTVVnnZ7fi5f-uYSHZxjDY


### activate user
POST http://localhost:3000/auth/activate
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWY4OTI2MTM2YzRlZTIxMDAzMGFlY2IiLCJzdGF0dXMiOnRydWUsImVtYWlsIjoicGF0aWVudEB4b3JkLmNvbSIsImlhdCI6MTY0MzY4MDM1MywiZXhwIjoxNjQzNjgyMTUzfQ.DowtDm3acFF10r3Z99lqRTLM-iL1cPWp6vt-ZFKXZHA

{
    "email": "patient@xord.com"
}