### register

POST http://localhost:3000/auth/register
content-type: application/json

{
    "name": "saltExample",
    "email": "salt@example.com",
    "password": "saltExample",
    "type": 0
}

### login

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email":"rija@example.com",
    "password":"rijaexample"
}

### accessing a protected route

GET http://localhost:3000/auth/protected
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmlqYUV4YW1wbGUiLCJzdWIiOiJyaWphQGV4YW1wbGUuY29tIiwiaWF0IjoxNjQzMjQ0Nzc4LCJleHAiOjE2NDMyNDQ4Mzh9._DqW6zXUa0ipkrrDkvtgWD3Z5n5cbKUH01jBNwZXLyo